plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
destination: docs
url: https://oliviercailloux.github.io
baseurl: /Exams
exclude:
  - README.adoc
  - Local notes.adoc
title: "Exam"
tagline: "Testez vos connaissances"
description: "Tester ses connaissances avec des questions Ã  choix multiples"
lang: fr

